# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.Qt import *
from PyQt5.QtWidgets import *
from PyQt5 import QtGui, QtWidgets
import PyQt5.QtCore as QtCore
from pathlib import Path
import configparser


class Ui_MainWindow(object):
    def parse_config(self):
        config = configparser.ConfigParser()
        config.read('config.ini')
        File_Path = config['Settings']['File_Path']
        self.a_value = File_Path
        #获取OK音效路径
        sound_path_OK = config['Settings']['sound_path_OK']
        self.OK_value = sound_path_OK
        # 获取NG音效路径
        sound_path_NG = config['Settings']['sound_path_NG']
        self.NG_value = sound_path_NG

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1490, 774, 364, 216))#视频界面
        font = QtGui.QFont()
        font.setPointSize(46)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        #self.label.hide()
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 1440, 980))#照片
        font = QtGui.QFont()
        font.setPointSize(46)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setLineWidth(3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1490, 10, 80, 60))#连接照相机
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1580, 10, 80, 60))#手动
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1760, 10, 80, 60))#自动
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1670, 10, 80, 60))#拍照
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        # 工单号
        self.text_label_1 = QLabel("工单号:", self.centralwidget)
        self.text_label_1.setGeometry(QtCore.QRect(1490, 200, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.text_label_1.setFont(font)
        # 工单号 输入框
        self.text_entry_1 = QLineEdit(self.centralwidget)
        self.text_entry_1.setGeometry(QtCore.QRect(1620, 200, 230, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.text_entry_1.setFont(font)
        #self.text_entry_1.setReadOnly(True)  # 只读
        # 产品型号
        self.text_label_2 = QLabel("产品型号:", self.centralwidget)
        self.text_label_2.setGeometry(QtCore.QRect(1490, 280, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.text_label_2.setFont(font)
        # 产品型号 输入框
        self.text_entry_2 = QLineEdit(self.centralwidget)
        self.text_entry_2.setGeometry(QtCore.QRect(1620, 280, 230, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.text_entry_2.setFont(font)
        #self.text_entry_2.setReadOnly(True)  # 只读
        # 数量/套
        self.text_label_3 = QLabel("数量/套:", self.centralwidget)
        self.text_label_3.setGeometry(QtCore.QRect(1490, 360, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.text_label_3.setFont(font)
        # 数量/套 输入框
        self.text_entry_3 = QLineEdit(self.centralwidget)
        self.text_entry_3.setGeometry(QtCore.QRect(1620, 360, 230, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.text_entry_3.setFont(font)
        #self.text_entry_3.setReadOnly(True)  # 只读
        # 生产班组
        self.text_label_4 = QLabel("生产班组:", self.centralwidget)
        self.text_label_4.setGeometry(QtCore.QRect(1490, 440, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.text_label_4.setFont(font)
        # 生产班组输入框
        self.text_entry_4 = QLineEdit(self.centralwidget)
        self.text_entry_4.setGeometry(QtCore.QRect(1620, 440, 230, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.text_entry_4.setFont(font)
        # 文件路径
        self.text_label_5 = QLabel("文件路径:", self.centralwidget)
        self.text_label_5.setGeometry(QtCore.QRect(1490, 520, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.text_label_5.setFont(font)
        # 文件路径输入框
        self.text_entry_5 = QLineEdit(self.centralwidget)
        self.text_entry_5.setGeometry(QtCore.QRect(1620, 520, 230, 50))
        font.setPointSize(20)
        self.text_entry_5.setText(self.a_value)
        #self.text_entry_5.setReadOnly(True)  # 只读
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.text_entry_5.setFont(font)
        # self.text_entry_5.setEchoMode(QLineEdit.PasswordText)

        # 存放音效地址
        self.text_entry_6 = QLineEdit(self.centralwidget)
        self.text_entry_6.setGeometry(QtCore.QRect(1620, 420, 230, 50))
        font.setPointSize(20)
        self.text_entry_6.setText(self.OK_value)
        self.text_entry_6.setReadOnly(True)
        self.text_entry_6.hide()
        # 存放音效地址
        self.text_entry_7 = QLineEdit(self.centralwidget)
        self.text_entry_7.setGeometry(QtCore.QRect(1620, 420, 230, 50))
        font.setPointSize(20)
        self.text_entry_7.setText(self.NG_value)
        self.text_entry_7.setReadOnly(True)
        self.text_entry_7.hide()

        # 扫描框
        self.text_entry_8 = QLineEdit(self.centralwidget)
        self.text_entry_8.setGeometry(QtCore.QRect(1490, 100, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.text_entry_8.setFont(font)

        # 是否使用VisonMaster
        self.text_label_6 = QLabel("VisionMaster:", self.centralwidget)
        self.text_label_6.setGeometry(QtCore.QRect(1490, 600, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(180)
        self.text_label_6.setFont(font)

        # 添加是否的选项控件
        self.comboBox_1 = QComboBox(self.centralwidget)
        self.comboBox_1.setGeometry(QtCore.QRect(1690, 600, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(180)
        self.comboBox_1.addItem("禁用")
        self.comboBox_1.addItem("启用")
        self.comboBox_1.setCurrentIndex(0)
        self.comboBox_1.setStyleSheet("QComboBox QAbstractItemView {"
                                      "font-size: 20px;"  # 设置下拉列表字体大小
                                      "width: 180px;"  # 设置下拉列表宽度
                                      "}")
        self.comboBox_1.setFont(font)

        # 频率时间
        self.text_label_7 = QLabel("频率时间:", self.centralwidget)
        self.text_label_7.setGeometry(QtCore.QRect(1490, 680, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(180)
        self.text_label_7.setFont(font)
        self.text_label_7.hide()

        # 频率时间 输入框
        self.text_entry_9 = QLineEdit(self.centralwidget)
        self.text_entry_9.setGeometry(QtCore.QRect(1620, 680, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.text_entry_9.setText("3")
        self.text_entry_9.setAlignment(Qt.AlignCenter)
        font.setBold(True)
        font.setWeight(75)
        self.text_entry_9.setFont(font)
        self.text_entry_9.hide()

        # 时间单位
        self.text_label_8 = QLabel(" 秒 ", self.centralwidget)
        self.text_label_8.setGeometry(QtCore.QRect(1770, 680, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(180)
        self.text_label_8.setFont(font)
        self.text_label_8.hide()

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.text_label_6 = QLabel("OK", self.centralwidget)
        self.text_label_6.setGeometry(QtCore.QRect(1300, 50, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(100)
        self.text_label_6.setFont(font)
        self.text_label_6.hide()

        self.text_label_7 = QLabel("NG", self.centralwidget)
        self.text_label_7.setGeometry(QtCore.QRect(1300, 50, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(100)
        self.text_label_7.setFont(font)
        self.text_label_7.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "手动界面"))
        self.label_2.setText(_translate("MainWindow", "自动界面"))
        self.pushButton.setText(_translate("MainWindow", "获取相机"))
        self.pushButton_2.setText(_translate("MainWindow", "手动"))
        self.pushButton_3.setText(_translate("MainWindow", "拍照"))
        self.pushButton_4.setText(_translate("MainWindow", "自动"))

